### PR TITLE
Adds an experimental version of an active prompt parser.

### PR DESCRIPTION
**Pull request by madrang**
For now, it's enabled by starting the prompt with !
But later a property selector should be added to the UI to allow users to select the `conditioning_transforms` mode and also allow plugins to send `conditioning_transforms` as JSON objects.

### CODE REVIEW

**Comment by cmdr2** [comment]
Hi @madrang Sorry if I'm missing it, but can you please point me to where the `!` (starts with) check is performed? Happy to merge this if existing prompts (without the `!` prefix) continue returning the exact same results.

**Comment by madrang** [comment]
> Hi @madrang Sorry if I'm missing it, but can you please point me to where the `!` (prefix) is checked? Happy to merge this if existing prompts (without the `!` prefix) continue returning the exact same results.

https://github.com/easydiffusion/sdkit/blob/6d8ef7a29d671aec9f74bb015a508a942c5665f3/sdkit/generate/tokenizer_conditionings.py#L219

**Comment by jsuelwald** [comment]
> Hi @madrang Sorry if I'm missing it, but can you please point me to where the `!` (prefix) is checked? Happy to merge this if existing prompts (without the `!` prefix) continue returning the exact same results.

I've tested the parser here in the past weeks as well. Prompts restored from text files will yield same result as before when the prompts didn't start with '!' as prefix

**Comment by cmdr2** [comment]
Thanks! Trying it out now, will merge to the `main` branch after testing and resolving the new conflicts (from merging the formatting-related PR).

**Pull request merged**
